#配置tomcat
server: 
    port: 8081
    session-timeout: 60
    tomcat:
        max-threads: 200
        uri-encoding: UTF-8
        basedir: /home/wgh/02_java/03_workspace/Test/cweb/temp
        
#配置log日志        
logging:
    path: /home/wgh/02_java/03_workspace/Test/cweb/logs/
    file: cweb.log
        
#配置spring数据源
spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/wgh
        username: wgh
        password: wgh
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select '*'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

#配置mybatis
mybatis: 
    sqlSessionFactoryBean: 
        mapperLocations: classpath:/com/br/cweb/mapper/*.xml
        typeAliasesPackage: com.br.cweb.model
    mapperScanner:
        basePackage: com.br.cweb.mapper
